#server:
#  port: 8082

#spring:
#  datasource:
#    driver-class-name: org.mariadb.jdbc.Driver
#    url: jdbc:mariadb://ip:port/databaseName?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&allowMultiQueries=true
#    username:
#    password:
#    hikari:
#      minimum-idle: 3
#      max-lifetime: 1800000
#      maximum-pool-size: 5

#mybatis-plus:
#  type-aliases-package: com/sgcc/applicationserver/entry #简化别名，用类的名字充当
#  mapper-locations: classpath:mapper/*.xml #类路径下
#  configuration:
#    map-underscore-to-camel-case: false
    # 是否开启自动驼峰命名规则（camel case）映射，即从经典数据库列名 A_COLUMN（下划线命名） 到经典 Java 属性名 aColumn（驼峰命名） 的类似映射
